"""initial schema: all tables, CHECK constraints, indexes and the append-only ledger trigger

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 10:41:28.764973
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('uq_categories_name_lower', 'categories', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='staff', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('manager', 'staff')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9]{2,5}$'", name=op.f('ck_warehouses_code_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_table('locations',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_locations_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('warehouse_id', 'name', name=op.f('uq_locations_warehouse_id'))
    )
    op.create_table('operation_sequences',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('next_value', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("type IN ('receipt', 'delivery', 'transfer', 'adjustment')", name=op.f('ck_operation_sequences_type')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_operation_sequences_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'type', name=op.f('pk_operation_sequences'))
    )
    op.create_table('password_resets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets'))
    )
    op.create_index('ix_password_resets_user_created', 'password_resets', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sku ~ '^[A-Z0-9][A-Z0-9_-]*$'", name=op.f('ck_products_sku_format')),
    sa.CheckConstraint("uom IN ('unit', 'kg', 'g', 'l', 'ml', 'm', 'box')", name=op.f('ck_products_uom')),
    sa.CheckConstraint('max_qty >= min_qty', name=op.f('ck_products_max_gte_min')),
    sa.CheckConstraint('min_qty >= 0', name=op.f('ck_products_min_qty_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_name_lower', 'products', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('operations',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('source_location_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_location_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_name', sa.String(length=160), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('validated_by', sa.BigInteger(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'done') = (validated_at IS NOT NULL)", name=op.f('ck_operations_done_has_validated_at')),
    sa.CheckConstraint("\n(type = 'receipt'    AND source_location_id IS NULL     AND destination_location_id IS NOT NULL)\nOR (type = 'delivery'   AND source_location_id IS NOT NULL AND destination_location_id IS NULL)\nOR (type = 'transfer'   AND source_location_id IS NOT NULL AND destination_location_id IS NOT NULL\n                        AND source_location_id <> destination_location_id)\nOR (type = 'adjustment' AND source_location_id IS NOT NULL AND destination_location_id IS NULL)\n", name=op.f('ck_operations_locations_by_type')),
    sa.CheckConstraint("status IN ('draft', 'waiting', 'ready', 'done', 'canceled')", name=op.f('ck_operations_status')),
    sa.CheckConstraint("type IN ('receipt', 'delivery', 'transfer', 'adjustment')", name=op.f('ck_operations_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_operations_created_by_users')),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], name=op.f('fk_operations_destination_location_id_locations')),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], name=op.f('fk_operations_source_location_id_locations')),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], name=op.f('fk_operations_validated_by_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_operations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('reference', name=op.f('uq_operations_reference'))
    )
    op.create_index('ix_operations_created_at', 'operations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_operations_destination_location_id'), 'operations', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_operations_source_location_id'), 'operations', ['source_location_id'], unique=False)
    op.create_index('ix_operations_type_status', 'operations', ['type', 'status'], unique=False)
    op.create_index('ix_operations_warehouse_status', 'operations', ['warehouse_id', 'status'], unique=False)
    op.create_table('stock_balances',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stock_balances_quantity_non_negative')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_balances_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_balances_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'location_id', name=op.f('pk_stock_balances'))
    )
    op.create_index(op.f('ix_stock_balances_location_id'), 'stock_balances', ['location_id'], unique=False)
    op.create_table('operation_lines',
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('counted_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('system_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(quantity IS NULL) <> (counted_quantity IS NULL)', name=op.f('ck_operation_lines_one_quantity_kind')),
    sa.CheckConstraint('counted_quantity >= 0', name=op.f('ck_operation_lines_counted_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_operation_lines_quantity_positive')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_lines_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_operation_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_lines')),
    sa.UniqueConstraint('operation_id', 'product_id', name=op.f('uq_operation_lines_operation_id'))
    )
    op.create_table('stock_ledger',
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_line_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('counterpart_location_id', sa.BigInteger(), nullable=True),
    sa.Column('movement_type', sa.String(length=12), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('receipt', 'delivery', 'transfer', 'adjustment')", name=op.f('ck_stock_ledger_movement_type')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_stock_ledger_balance_after_non_negative')),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_stock_ledger_delta_non_zero')),
    sa.ForeignKeyConstraint(['counterpart_location_id'], ['locations.id'], name=op.f('fk_stock_ledger_counterpart_location_id_locations')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_ledger_created_by_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_ledger_location_id_locations')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_stock_ledger_operation_id_operations')),
    sa.ForeignKeyConstraint(['operation_line_id'], ['operation_lines.id'], name=op.f('fk_stock_ledger_operation_line_id_operation_lines')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_ledger_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_ledger'))
    )
    op.create_index('ix_stock_ledger_location_created', 'stock_ledger', ['location_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_ledger_operation_id'), 'stock_ledger', ['operation_id'], unique=False)
    op.create_index('ix_stock_ledger_product_created', 'stock_ledger', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: the stock ledger is append-only. Corrections are new operations, never edits.
    op.execute(
        """
        CREATE FUNCTION forbid_ledger_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'stock_ledger is append-only (op=%)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER stock_ledger_append_only
        BEFORE UPDATE OR DELETE ON stock_ledger
        FOR EACH ROW EXECUTE FUNCTION forbid_ledger_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS stock_ledger_append_only ON stock_ledger")
    op.execute("DROP FUNCTION IF EXISTS forbid_ledger_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_ledger_product_created', table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_operation_id'), table_name='stock_ledger')
    op.drop_index('ix_stock_ledger_location_created', table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_table('operation_lines')
    op.drop_index(op.f('ix_stock_balances_location_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index('ix_operations_warehouse_status', table_name='operations')
    op.drop_index('ix_operations_type_status', table_name='operations')
    op.drop_index(op.f('ix_operations_source_location_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_destination_location_id'), table_name='operations')
    op.drop_index('ix_operations_created_at', table_name='operations')
    op.drop_table('operations')
    op.drop_index('ix_products_name_lower', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_password_resets_user_created', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_table('operation_sequences')
    op.drop_table('locations')
    op.drop_table('warehouses')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_categories_name_lower', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
